package com.mycompany.registroinasistencias.GUI;
import com.mycompany.registroinasistencias.Logica.Asignatura;
import com.mycompany.registroinasistencias.Logica.Controladora;
import com.mycompany.registroinasistencias.Logica.Docente;
import java.util.List;
import com.mycompany.registroinasistencias.Logica.GestorInasistencia;
import com.mycompany.registroinasistencias.Logica.Inasistencia;
import javax.swing.table.DefaultTableModel;

public class AbsenceRegistry extends javax.swing.JFrame {
    Controladora control = new Controladora();
    GestorInasistencia gi = new GestorInasistencia();
    private MainMenu mainMenu;
    private Display display;
    private List<Docente> listaDocentes;
    private List<Inasistencia> listaInasistencias;
    
    private void cargarComboDocentes() {
        cbDocenteInasistencias.removeAllItems();
        listaDocentes = control.traerDocentes();
        
        if(listaDocentes != null && !listaDocentes.isEmpty()) {
            for(Docente doc : listaDocentes) {
                cbDocenteInasistencias.addItem(doc.getNombreDocente());
            }
        }
    }
    
    private void cargarTablaInasistencias() {
        DefaultTableModel tablaModelInas = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        String titulos[] = {"Docente", "Asignatura", "Grupo afectado", "Día comienzo", "Día fin"};
        tablaModelInas.setColumnIdentifiers(titulos);
        
        listaInasistencias = control.traerInasistencias();
        
        System.out.println("Cantidad de inasistencias: " + 
    (listaInasistencias != null ? listaInasistencias.size() : "null"));
        
        if(listaInasistencias != null && !listaInasistencias.isEmpty()){
            for(Inasistencia i: listaInasistencias){
                List<String> listaGruposAfectados = gi.calcularGruposAfectados(i);
                
                List<Asignatura> asignaturas = i.getDocente().getAsignaturas();
                
                if(listaGruposAfectados != null && !listaGruposAfectados.isEmpty()) {
                    for(String grupo : listaGruposAfectados) {
                        String asignaturaNombre = "";
                        for(Asignatura asig : asignaturas) {
                            if(asig.getGrupo().equals(grupo)) {
                                asignaturaNombre = asig.getNombreAsignatura();
                                break;
                            }
                        }
                        
                        Object[] object = {
                            i.getDocente().getNombreDocente(),
                            asignaturaNombre,
                            grupo,
                            i.getDesde(), 
                            i.getHasta()
                        };
                        tablaModelInas.addRow(object);
                    }
                } else {
                    Object[] object = {
                        i.getDocente().getNombreDocente(),
                        "",
                        "Ninguno",
                        i.getDesde(), 
                        i.getHasta()
                    };
                    tablaModelInas.addRow(object);
                }
            }         
        }
        
        tablaInasistencias.setModel(tablaModelInas);
    }
    
    public void setMainMenu(MainMenu mainMenu) {
        this.mainMenu = mainMenu;
    }
    
    public void setDisplay(Display display) {
        this.display = display;
    }
    
    public AbsenceRegistry() {
        initComponents();
        cargarComboDocentes();  
        cargarTablaInasistencias();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerAbsenceRegistry = new javax.swing.JLabel();
        textFieldDesde = new javax.swing.JTextField();
        textFieldHasta = new javax.swing.JTextField();
        labelTeacher = new javax.swing.JLabel();
        labelFrom = new javax.swing.JLabel();
        labelTo = new javax.swing.JLabel();
        buttonAddAbsence = new javax.swing.JButton();
        buttonReturn = new javax.swing.JButton();
        buttonShowDisplay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInasistencias = new javax.swing.JTable();
        buttonCloseDisplay = new javax.swing.JButton();
        cbDocenteInasistencias = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        headerAbsenceRegistry.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        headerAbsenceRegistry.setText("Registro de Inasistencias");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 63, 0, 0);
        getContentPane().add(headerAbsenceRegistry, gridBagConstraints);

        textFieldDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDesdeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 101;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 18, 0, 0);
        getContentPane().add(textFieldDesde, gridBagConstraints);

        textFieldHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldHastaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 101;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        getContentPane().add(textFieldHasta, gridBagConstraints);

        labelTeacher.setText("Docente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 130, 0, 0);
        getContentPane().add(labelTeacher, gridBagConstraints);

        labelFrom.setText("Desde");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 130, 0, 0);
        getContentPane().add(labelFrom, gridBagConstraints);

        labelTo.setText("Hasta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 130, 0, 0);
        getContentPane().add(labelTo, gridBagConstraints);

        buttonAddAbsence.setText("Agregar");
        buttonAddAbsence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddAbsenceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        getContentPane().add(buttonAddAbsence, gridBagConstraints);

        buttonReturn.setText("Volver");
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 41, 6, 6);
        getContentPane().add(buttonReturn, gridBagConstraints);

        buttonShowDisplay.setText("Mostrar");
        buttonShowDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowDisplayActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 6, 0);
        getContentPane().add(buttonShowDisplay, gridBagConstraints);

        tablaInasistencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaInasistencias);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 661;
        gridBagConstraints.ipady = 129;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 6);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        buttonCloseDisplay.setText("Cerrar Display");
        buttonCloseDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseDisplayActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 6, 0);
        getContentPane().add(buttonCloseDisplay, gridBagConstraints);

        cbDocenteInasistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDocenteInasistenciasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 93;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 18, 0, 0);
        getContentPane().add(cbDocenteInasistencias, gridBagConstraints);

        jLabel1.setText("Ingrese formato: yyyy-mm-dd");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = -9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonShowDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowDisplayActionPerformed
        display.setVisible(true);
    }//GEN-LAST:event_buttonShowDisplayActionPerformed

    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        mainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonReturnActionPerformed
 
    private void buttonCloseDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseDisplayActionPerformed
        display.setVisible(false);
    }//GEN-LAST:event_buttonCloseDisplayActionPerformed

    private void cbDocenteInasistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDocenteInasistenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDocenteInasistenciasActionPerformed

    private void textFieldDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDesdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDesdeActionPerformed

    private void textFieldHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldHastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldHastaActionPerformed

    private void buttonAddAbsenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddAbsenceActionPerformed
        int index = cbDocenteInasistencias.getSelectedIndex();
        
        if (index == -1 || listaDocentes == null || listaDocentes.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor seleccione un docente", 
                "Error", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String desde = textFieldDesde.getText().trim();
        String hasta = textFieldHasta.getText().trim();
        
        if (desde.isEmpty() || hasta.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor complete las fechas de inicio y fin", 
                "Error", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Docente docente = listaDocentes.get(index);
        control.crearInasistencia(docente.getCI(), desde, hasta);
        
        textFieldDesde.setText("");
        textFieldHasta.setText("");
        cbDocenteInasistencias.setSelectedIndex(-1);
        
        cargarTablaInasistencias();
        
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Inasistencia registrada correctamente", 
            "Éxito", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonAddAbsenceActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddAbsence;
    private javax.swing.JButton buttonCloseDisplay;
    private javax.swing.JButton buttonReturn;
    private javax.swing.JButton buttonShowDisplay;
    private javax.swing.JComboBox<String> cbDocenteInasistencias;
    private javax.swing.JLabel headerAbsenceRegistry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFrom;
    private javax.swing.JLabel labelTeacher;
    private javax.swing.JLabel labelTo;
    private javax.swing.JTable tablaInasistencias;
    private javax.swing.JTextField textFieldDesde;
    private javax.swing.JTextField textFieldHasta;
    // End of variables declaration//GEN-END:variables
}
