package com.mycompany.registroinasistencias.GUI;

import com.mycompany.registroinasistencias.Logica.Controladora;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Dario
 */
public class AccountOptions extends javax.swing.JFrame {
    Controladora control = new Controladora();
    Login login = new Login();
    private MainMenu mainMenu;
    private CreateAccount createAccount;
    
    public void setMainMenu(MainMenu mainMenu) {
        this.mainMenu = mainMenu;
    }
    
    public void setCreateAccount(CreateAccount createAccount) {
        this.createAccount = createAccount;
    }
    
    /**
     * Creates new form AccountOptions
     */
    public AccountOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        labelCurrentPassword = new javax.swing.JLabel();
        labelNewPassword = new javax.swing.JLabel();
        labelRepeatPassword = new javax.swing.JLabel();
        txtpasswordFieldNew = new javax.swing.JPasswordField();
        txtpasswordFieldNewRepeat = new javax.swing.JPasswordField();
        buttonCHangePassword = new javax.swing.JButton();
        buttonCreateAccountOptions = new javax.swing.JButton();
        buttonReturn = new javax.swing.JButton();
        txtpasswordFieldCurrent = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Opciones de Cuenta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 146, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        labelCurrentPassword.setText("Contraseña actual");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 146, 0, 0);
        getContentPane().add(labelCurrentPassword, gridBagConstraints);

        labelNewPassword.setText("Nueva contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 146, 0, 0);
        getContentPane().add(labelNewPassword, gridBagConstraints);

        labelRepeatPassword.setText("Repita contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 146, 0, 0);
        getContentPane().add(labelRepeatPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        getContentPane().add(txtpasswordFieldNew, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        getContentPane().add(txtpasswordFieldNewRepeat, gridBagConstraints);

        buttonCHangePassword.setText("Cambiar");
        buttonCHangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCHangePasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        getContentPane().add(buttonCHangePassword, gridBagConstraints);

        buttonCreateAccountOptions.setText("Crear cuenta");
        buttonCreateAccountOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateAccountOptionsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 18, 0, 0);
        getContentPane().add(buttonCreateAccountOptions, gridBagConstraints);

        buttonReturn.setText("Volver");
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(67, 61, 6, 6);
        getContentPane().add(buttonReturn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 18, 0, 0);
        getContentPane().add(txtpasswordFieldCurrent, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        mainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonReturnActionPerformed

    private void buttonCreateAccountOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateAccountOptionsActionPerformed
        createAccount.setVolverToAccountOptions(true);
        createAccount.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_buttonCreateAccountOptionsActionPerformed

    private void buttonCHangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCHangePasswordActionPerformed
        String anteriorPassword = txtpasswordFieldCurrent.getText();
        String nuevaPassword = txtpasswordFieldNew.getText();
        String repeatPassword = txtpasswordFieldNewRepeat.getText();
        
        if(!nuevaPassword.equals(repeatPassword)){
            mostrarMensaje("La contraseñas no son iguales", "Error", "Error al cambiar contraseña");
        }else{
            if(control.verificarCI(login.devuelveCI())){
                
            }
            
            
        }
        
    }//GEN-LAST:event_buttonCHangePasswordActionPerformed

    /**
     * @param args the command line arguments
     */

    
    public void mostrarMensaje(String mensaje, String tipo, String titulo){
                JOptionPane optionPane = new JOptionPane(mensaje);
                if(tipo.equals("Info")){
                        optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
                }
                else if(tipo.equals("Error")){
                    optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
                }
                JDialog dialog = optionPane.createDialog(titulo);
                dialog.setAlwaysOnTop(true);
                dialog.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCHangePassword;
    private javax.swing.JButton buttonCreateAccountOptions;
    private javax.swing.JButton buttonReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCurrentPassword;
    private javax.swing.JLabel labelNewPassword;
    private javax.swing.JLabel labelRepeatPassword;
    private javax.swing.JPasswordField txtpasswordFieldCurrent;
    private javax.swing.JPasswordField txtpasswordFieldNew;
    private javax.swing.JPasswordField txtpasswordFieldNewRepeat;
    // End of variables declaration//GEN-END:variables
}

