package com.mycompany.registroinasistencias.GUI;

import com.mycompany.registroinasistencias.Logica.Controladora;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Dario
 */
public class AccountOptions extends javax.swing.JFrame {
    Controladora control = new Controladora();
    Login login = new Login();
    private MainMenu mainMenu;
    private CreateAccount createAccount;
    
    public void setMainMenu(MainMenu mainMenu) {
        this.mainMenu = mainMenu;
    }
    
    public void setCreateAccount(CreateAccount createAccount) {
        this.createAccount = createAccount;
    }
    
    /**
     * Creates new form AccountOptions
     */
    public AccountOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelCurrentPassword = new javax.swing.JLabel();
        labelNewPassword = new javax.swing.JLabel();
        labelRepeatPassword = new javax.swing.JLabel();
        txtpasswordFieldNew = new javax.swing.JPasswordField();
        txtpasswordFieldNewRepeat = new javax.swing.JPasswordField();
        buttonCHangePassword = new javax.swing.JButton();
        buttonCreateAccountOptions = new javax.swing.JButton();
        buttonReturn = new javax.swing.JButton();
        txtpasswordFieldCurrent = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Opciones de Cuenta");

        labelCurrentPassword.setText("Contraseña actual");

        labelNewPassword.setText("Nueva contraseña");

        labelRepeatPassword.setText("Repita contraseña");

        buttonCHangePassword.setText("Cambiar");
        buttonCHangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCHangePasswordActionPerformed(evt);
            }
        });

        buttonCreateAccountOptions.setText("Crear cuenta");
        buttonCreateAccountOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateAccountOptionsActionPerformed(evt);
            }
        });

        buttonReturn.setText("Volver");
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNewPassword)
                                    .addComponent(labelCurrentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelRepeatPassword))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttonCHangePassword)
                                    .addComponent(txtpasswordFieldNew, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(txtpasswordFieldNewRepeat)
                                    .addComponent(buttonCreateAccountOptions)
                                    .addComponent(txtpasswordFieldCurrent)))
                            .addComponent(jLabel1))
                        .addGap(0, 133, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonReturn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCurrentPassword)
                    .addComponent(txtpasswordFieldCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpasswordFieldNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNewPassword))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRepeatPassword)
                    .addComponent(txtpasswordFieldNewRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonCHangePassword)
                .addGap(44, 44, 44)
                .addComponent(buttonCreateAccountOptions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(buttonReturn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        mainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonReturnActionPerformed

    private void buttonCreateAccountOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateAccountOptionsActionPerformed
        createAccount.setVolverToAccountOptions(true);
        createAccount.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_buttonCreateAccountOptionsActionPerformed

    private void buttonCHangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCHangePasswordActionPerformed
        String anteriorPassword = txtpasswordFieldCurrent.getText();
        String nuevaPassword = txtpasswordFieldNew.getText();
        String repeatPassword = txtpasswordFieldNewRepeat.getText();
        
        if(!nuevaPassword.equals(repeatPassword)){
            mostrarMensaje("La contraseñas no son iguales", "Error", "Error al cambiar contraseña");
        }else{
            if(control.verificarCI(login.devuelveCI())){
                
            }
            
            
        }
        
    }//GEN-LAST:event_buttonCHangePasswordActionPerformed

    /**
     * @param args the command line arguments
     */

    
    public void mostrarMensaje(String mensaje, String tipo, String titulo){
                JOptionPane optionPane = new JOptionPane(mensaje);
                if(tipo.equals("Info")){
                        optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
                }
                else if(tipo.equals("Error")){
                    optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
                }
                JDialog dialog = optionPane.createDialog(titulo);
                dialog.setAlwaysOnTop(true);
                dialog.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCHangePassword;
    private javax.swing.JButton buttonCreateAccountOptions;
    private javax.swing.JButton buttonReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCurrentPassword;
    private javax.swing.JLabel labelNewPassword;
    private javax.swing.JLabel labelRepeatPassword;
    private javax.swing.JPasswordField txtpasswordFieldCurrent;
    private javax.swing.JPasswordField txtpasswordFieldNew;
    private javax.swing.JPasswordField txtpasswordFieldNewRepeat;
    // End of variables declaration//GEN-END:variables
}

