package com.mycompany.registroinasistencias.GUI;

import com.mycompany.registroinasistencias.Logica.Controladora;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Dario
 */
public class CreateAccount extends javax.swing.JFrame {
    Controladora control = new Controladora();
    private MainMenu mainMenu;
    private Login login;
    
    public void setMainMenu(MainMenu mainMenu) {
        this.mainMenu = mainMenu;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    
    public CreateAccount() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        textFieldCI = new javax.swing.JTextField();
        passwordFieldPassword = new javax.swing.JPasswordField();
        passwordFieldRepeat = new javax.swing.JPasswordField();
        buttonCreateAccount = new javax.swing.JButton();
        buttonReturn = new javax.swing.JButton();
        labelCI = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        labelRepeatPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        textFieldCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCIActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 108;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(75, 18, 0, 0);
        getContentPane().add(textFieldCI, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 108;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 18, 0, 0);
        getContentPane().add(passwordFieldPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 108;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        getContentPane().add(passwordFieldRepeat, gridBagConstraints);

        buttonCreateAccount.setText("Crear");
        buttonCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateAccountActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        getContentPane().add(buttonCreateAccount, gridBagConstraints);

        buttonReturn.setText("Volver");
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(135, 85, 6, 6);
        getContentPane().add(buttonReturn, gridBagConstraints);

        labelCI.setText("Número de Cédula");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(78, 55, 0, 0);
        getContentPane().add(labelCI, gridBagConstraints);

        labelPassword.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 55, 0, 0);
        getContentPane().add(labelPassword, gridBagConstraints);

        labelRepeatPassword.setText("Repita la contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 55, 0, 0);
        getContentPane().add(labelRepeatPassword, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonReturnActionPerformed

    private void buttonCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateAccountActionPerformed
        String ci = textFieldCI.getText();

        String password = passwordFieldPassword.getText();
        String passwordRepeat = passwordFieldRepeat.getText();
        
        if(!ci.equals("") && !password.equals("")){
                if(password.equals(passwordRepeat)){
                    
                    login.setVisible(true);
                    this.setVisible(false);
                    control.guardarUsuario(ci, password);
                }else{
                    mostrarMensaje("La contraseña debe ser la misma en ambos campos", "Error", "Error al registrar contraseña");
                }
        }else{
            mostrarMensaje("Complete todos los campos", "Error", "Error al login");
        }
    }//GEN-LAST:event_buttonCreateAccountActionPerformed

    private void textFieldCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCIActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreateAccount;
    private javax.swing.JButton buttonReturn;
    private javax.swing.JLabel labelCI;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelRepeatPassword;
    private javax.swing.JPasswordField passwordFieldPassword;
    private javax.swing.JPasswordField passwordFieldRepeat;
    private javax.swing.JTextField textFieldCI;
    // End of variables declaration//GEN-END:variables

public void mostrarMensaje(String mensaje, String tipo, String titulo){
                JOptionPane optionPane = new JOptionPane(mensaje);
                if(tipo.equals("Info")){
                        optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
                }
                else if(tipo.equals("Error")){
                    optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
                }
                JDialog dialog = optionPane.createDialog(titulo);
                dialog.setAlwaysOnTop(true);
                dialog.setVisible(true);
    }

}
