package com.mycompany.registroinasistencias.GUI;

import com.mycompany.registroinasistencias.Logica.Asignatura;
import com.mycompany.registroinasistencias.Logica.Controladora;
import com.mycompany.registroinasistencias.Logica.Docente;
import com.mycompany.registroinasistencias.Logica.GestorInasistencia;
import com.mycompany.registroinasistencias.Logica.Inasistencia;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dario
 */
public class Display extends javax.swing.JFrame {

    Controladora control = new Controladora();
        private List<Docente> listaDocentes;
    private List<Inasistencia> listaInasistencias;
     GestorInasistencia gi = new GestorInasistencia();
    /**
     * Creates new form Display
     */
    public Display() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDisplay = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Inasistencias Docentes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 158, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        tablaDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaDisplay.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaDisplayAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tablaDisplay);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 675;
        gridBagConstraints.ipady = 312;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(35, 6, 6, 6);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaDisplayAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaDisplayAncestorAdded
        
    }//GEN-LAST:event_tablaDisplayAncestorAdded

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       cargarTablaDisplay();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDisplay;
    // End of variables declaration//GEN-END:variables



 private void cargarTablaDisplay() {
        DefaultTableModel tablaModelInas = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        String titulos[] = {"Docente", "Asignatura", "Grupo afectado", "Día comienzo", "Día fin"};
        tablaModelInas.setColumnIdentifiers(titulos);
        
        listaInasistencias = control.traerInasistencias();
        
        System.out.println("Cantidad de inasistencias: " + 
    (listaInasistencias != null ? listaInasistencias.size() : "null"));
        
        if(listaInasistencias != null && !listaInasistencias.isEmpty()){
            for(Inasistencia i: listaInasistencias){
                List<String> listaGruposAfectados = gi.calcularGruposAfectados(i);
                
                List<Asignatura> asignaturas = i.getDocente().getAsignaturas();
                
                if(listaGruposAfectados != null && !listaGruposAfectados.isEmpty()) {
                    for(String grupo : listaGruposAfectados) {
                        String asignaturaNombre = "";
                        for(Asignatura asig : asignaturas) {
                            if(asig.getGrupo().equals(grupo)) {
                                asignaturaNombre = asig.getNombreAsignatura();
                                break;
                            }
                        }
                        
                        Object[] object = {
                            i.getDocente().getNombreDocente(),
                            asignaturaNombre,
                            grupo,
                            i.getDesde(), 
                            i.getHasta()
                        };
                        tablaModelInas.addRow(object);
                    }
                } else {
                    Object[] object = {
                        i.getDocente().getNombreDocente(),
                        "",
                        "Ninguno",
                        i.getDesde(), 
                        i.getHasta()
                    };
                    tablaModelInas.addRow(object);
                }
            }         
        }
        
        tablaDisplay.setModel(tablaModelInas);
    }
}
