package com.mycompany.registroinasistencias.GUI;

import com.mycompany.registroinasistencias.Logica.Controladora;
import java.util.Set;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Dario
 */
public class Login extends javax.swing.JFrame {
    Controladora control = new Controladora();
    //lo ponemos como una variable global para que pueda ser utilizada en otro momento dentro de la sesions
    String ci = "";
    private MainMenu mainMenu;
    private CreateAccount createAccount;
    private Display display;
    
    public void setMainMenu(MainMenu mainMenu) {
        this.mainMenu = mainMenu;
    }
    
    public void setCreateAccount(CreateAccount createAccount) {
        this.createAccount = createAccount;
    }

    public void setDisplay(Display display) {
        this.display = display;
    }
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
       


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanelcontenedorr = new javax.swing.JPanel();
        buttonLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelUsernameLogin = new javax.swing.JLabel();
        textfieldCiLogin = new javax.swing.JTextField();
        labelPasswordLogin = new javax.swing.JLabel();
        buttonCreateAccount = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        passwordfieldLogin = new javax.swing.JPasswordField();
        butonExitLogin = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelcontenedorr.setLayout(new java.awt.GridBagLayout());

        buttonLogin.setText("Ingresar");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(12, 78, 0, 0);
        jPanelcontenedorr.add(buttonLogin, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenido a AusentApp");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = -14;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 72, 0, 0);
        jPanelcontenedorr.add(jLabel1, gridBagConstraints);

        labelUsernameLogin.setText("Cedula");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.insets = new java.awt.Insets(18, 92, 0, 0);
        jPanelcontenedorr.add(labelUsernameLogin, gridBagConstraints);

        textfieldCiLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldCiLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 159;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 0);
        jPanelcontenedorr.add(textfieldCiLogin, gridBagConstraints);

        labelPasswordLogin.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.insets = new java.awt.Insets(18, 83, 0, 0);
        jPanelcontenedorr.add(labelPasswordLogin, gridBagConstraints);

        buttonCreateAccount.setText("Crear");
        buttonCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateAccountActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.insets = new java.awt.Insets(12, 7, 6, 0);
        jPanelcontenedorr.add(buttonCreateAccount, gridBagConstraints);

        jLabel4.setText("No tienes una cuenta?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.insets = new java.awt.Insets(10, 32, 0, 6);
        jPanelcontenedorr.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 159;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 0);
        jPanelcontenedorr.add(passwordfieldLogin, gridBagConstraints);

        butonExitLogin.setText("Salir");
        butonExitLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonExitLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 6, 0);
        jPanelcontenedorr.add(butonExitLogin, gridBagConstraints);

        getContentPane().add(jPanelcontenedorr, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldCiLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldCiLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldCiLoginActionPerformed

    private void buttonCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateAccountActionPerformed
        createAccount.setVolverToAccountOptions(false);
        createAccount.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_buttonCreateAccountActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
         ci = textfieldCiLogin.getText();
        String password = passwordfieldLogin.getText();
        if(control.verificarCI(ci)){
            if(control.verificarUsuario(ci, password)){
                mainMenu.setVisible(true);
                this.setVisible(false);
            }else{
                mostrarMensaje("Usuario incorrecto", "Error", "Usuario no valido");
            }
        }else{
            mostrarMensaje("No existe la Cedula, ingrese de nuevo", "Error", "Cedula incorrecta");
        }
        
        
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void butonExitLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonExitLoginActionPerformed
        
        display.dispose();
        this.dispose();
        System.exit(0);
        
    }//GEN-LAST:event_butonExitLoginActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonExitLogin;
    private javax.swing.JButton buttonCreateAccount;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelcontenedorr;
    private javax.swing.JLabel labelPasswordLogin;
    private javax.swing.JLabel labelUsernameLogin;
    private javax.swing.JPasswordField passwordfieldLogin;
    private javax.swing.JTextField textfieldCiLogin;
    // End of variables declaration//GEN-END:variables

public void mostrarMensaje(String mensaje, String tipo, String titulo){
                JOptionPane optionPane = new JOptionPane(mensaje);
                if(tipo.equals("Info")){
                        optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
                }
                else if(tipo.equals("Error")){
                    optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
                }
                JDialog dialog = optionPane.createDialog(titulo);
                dialog.setAlwaysOnTop(true);
                dialog.setVisible(true);
    }

public String devuelveCI(){
    return ci;
}
}
