package com.mycompany.registroinasistencias.GUI;

/**
 *
 * @author Dario
 */
public class MainMenu extends javax.swing.JFrame {

    private AbsenceRegistry absenceRegistry;
    private TeacherRegistry teacherRegistry;
    private Display display;
    
    public void setAbsenceRegistry(AbsenceRegistry abasenceRegistry) {
        this.absenceRegistry = abasenceRegistry;
    }
    
    public void setTeacherRegistry(TeacherRegistry teacherRegistry) {
        this.teacherRegistry = teacherRegistry;
    }

    public void setDisplay(Display display) {
        this.display = display;
    }
    
    public MainMenu() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainMenuHeader = new javax.swing.JLabel();
        buttonTeacherRegistry = new javax.swing.JButton();
        buttonAbsenceRegistry = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mainMenuHeader.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        mainMenuHeader.setText("Menú Principal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 141, 0, 0);
        getContentPane().add(mainMenuHeader, gridBagConstraints);

        buttonTeacherRegistry.setText("Fichas Docentes");
        buttonTeacherRegistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTeacherRegistryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 191, 0, 0);
        getContentPane().add(buttonTeacherRegistry, gridBagConstraints);

        buttonAbsenceRegistry.setText("Ingreso Inasistencias");
        buttonAbsenceRegistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAbsenceRegistryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 191, 0, 0);
        getContentPane().add(buttonAbsenceRegistry, gridBagConstraints);

        buttonExit.setText("Salir");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(144, 53, 6, 6);
        getContentPane().add(buttonExit, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTeacherRegistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTeacherRegistryActionPerformed
        teacherRegistry.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonTeacherRegistryActionPerformed

    private void buttonAbsenceRegistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAbsenceRegistryActionPerformed
        absenceRegistry.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonAbsenceRegistryActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
       display.dispose();
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbsenceRegistry;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonTeacherRegistry;
    private javax.swing.JLabel mainMenuHeader;
    // End of variables declaration//GEN-END:variables
}
