/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.registroinasistencias.GUI;

/**
 *
 * @author Dario
 */
public class MainMenu extends javax.swing.JFrame {

    private AbsenceRegistry absenceRegistry;
    private AccountOptions accountOptions;
    private TeacherRegistry teacherRegistry;
    private Display display;
    
    public void setAbsenceRegistry(AbsenceRegistry abasenceRegistry) {
        this.absenceRegistry = abasenceRegistry;
    }
    
    public void setAccountOptions(AccountOptions accountOptions) {
        this.accountOptions = accountOptions;
    }
    
    public void setTeacherRegistry(TeacherRegistry teacherRegistry) {
        this.teacherRegistry = teacherRegistry;
    }

    public void setDisplay(Display display) {
        this.display = display;
    }
    
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuHeader = new javax.swing.JLabel();
        buttonTeacherRegistry = new javax.swing.JButton();
        buttonAbsenceRegistry = new javax.swing.JButton();
        buttonAccountOptions = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainMenuHeader.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        mainMenuHeader.setText("Menú Principal");

        buttonTeacherRegistry.setText("Fichas Docentes");
        buttonTeacherRegistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTeacherRegistryActionPerformed(evt);
            }
        });

        buttonAbsenceRegistry.setText("Ingreso Inasistencias");
        buttonAbsenceRegistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAbsenceRegistryActionPerformed(evt);
            }
        });

        buttonAccountOptions.setText("Opciones de Cuenta");
        buttonAccountOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAccountOptionsActionPerformed(evt);
            }
        });

        buttonExit.setText("Salir");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonAccountOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAbsenceRegistry)
                            .addComponent(buttonTeacherRegistry, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mainMenuHeader)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonExit)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(mainMenuHeader)
                .addGap(41, 41, 41)
                .addComponent(buttonTeacherRegistry)
                .addGap(18, 18, 18)
                .addComponent(buttonAbsenceRegistry)
                .addGap(18, 18, 18)
                .addComponent(buttonAccountOptions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(buttonExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTeacherRegistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTeacherRegistryActionPerformed
        teacherRegistry.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonTeacherRegistryActionPerformed

    private void buttonAbsenceRegistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAbsenceRegistryActionPerformed
        absenceRegistry.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonAbsenceRegistryActionPerformed

    private void buttonAccountOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAccountOptionsActionPerformed
        accountOptions.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonAccountOptionsActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
       display.dispose();
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbsenceRegistry;
    private javax.swing.JButton buttonAccountOptions;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonTeacherRegistry;
    private javax.swing.JLabel mainMenuHeader;
    // End of variables declaration//GEN-END:variables
}
