package com.mycompany.registroinasistencias.GUI;

import com.mycompany.registroinasistencias.Logica.Asignatura;
import com.mycompany.registroinasistencias.Logica.Controladora;
import com.mycompany.registroinasistencias.Logica.Docente;
import com.mycompany.registroinasistencias.Logica.Turno;
import java.time.DayOfWeek;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dario
 */
public class TeacherRegistry extends javax.swing.JFrame {

    Controladora control = new Controladora();
    private MainMenu mainMenu;
    private Display display;
    private List<Docente> listaDocentes;
    
    public void setMainMenu(MainMenu mainMenu) {
        this.mainMenu = mainMenu;
    }
    
    public void setDisplay(Display display) {
        this.display = display;
    }
    
    public TeacherRegistry() {
        initComponents();        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerTeacherRegistry = new javax.swing.JLabel();
        buttonReturn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        headerAddTeacher = new javax.swing.JLabel();
        textFieldNameTeacher = new javax.swing.JTextField();
        textFieldCI = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        labelCI = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doceTabla = new javax.swing.JTable();
        buttonAddTeacher = new javax.swing.JButton();
        buttonDeleteTeacher = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        headerAddSubject = new javax.swing.JLabel();
        labelTeacherDropdown = new javax.swing.JLabel();
        cbElegirDocente = new javax.swing.JComboBox<>();
        labelSubjectName = new javax.swing.JLabel();
        textFieldGrupo = new javax.swing.JTextField();
        labelGroup = new javax.swing.JLabel();
        textFieldMateria = new javax.swing.JTextField();
        cbElegirDia = new javax.swing.JComboBox<>();
        cbElegirTurno = new javax.swing.JComboBox<>();
        buttonAgregarAsignatura = new javax.swing.JButton();
        labelWeekDays = new javax.swing.JLabel();
        labelGroup1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        asigTabla = new javax.swing.JTable();
        buttonDeleteMateria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        headerTeacherRegistry.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        headerTeacherRegistry.setText("Fichas Docentes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 455, 0, 0);
        getContentPane().add(headerTeacherRegistry, gridBagConstraints);

        buttonReturn.setText("Volver");
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 164, 0, 0);
        getContentPane().add(buttonReturn, gridBagConstraints);

        headerAddTeacher.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        headerAddTeacher.setText("Agregar Docente Nuevo");

        textFieldNameTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNameTeacherActionPerformed(evt);
            }
        });

        textFieldCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCIActionPerformed(evt);
            }
        });

        labelName.setText("Nombre");

        labelCI.setText("Cédula");

        doceTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(doceTabla);

        buttonAddTeacher.setText("Agregar");
        buttonAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddTeacherActionPerformed(evt);
            }
        });

        buttonDeleteTeacher.setText("Borrar");
        buttonDeleteTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteTeacherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(headerAddTeacher)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonDeleteTeacher)
                        .addGap(112, 112, 112)
                        .addComponent(buttonAddTeacher)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                .addGap(90, 90, 90)
                                .addComponent(textFieldNameTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelCI, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textFieldCI, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerAddTeacher)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(textFieldNameTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCI)
                    .addComponent(textFieldCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(151, 151, 151)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddTeacher)
                    .addComponent(buttonDeleteTeacher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 6, 6, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        headerAddSubject.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        headerAddSubject.setText("Agregar Asignatura");

        labelTeacherDropdown.setText("Docente");

        cbElegirDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbElegirDocenteActionPerformed(evt);
            }
        });

        labelSubjectName.setText("Materia");

        labelGroup.setText("Grupo");

        cbElegirDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbElegirDiaActionPerformed(evt);
            }
        });

        cbElegirTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbElegirTurnoActionPerformed(evt);
            }
        });

        buttonAgregarAsignatura.setText("Agregar");
        buttonAgregarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarAsignaturaActionPerformed(evt);
            }
        });

        labelWeekDays.setText("Dia");

        labelGroup1.setText("Turno");

        asigTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(asigTabla);

        buttonDeleteMateria.setText("Borrar");
        buttonDeleteMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelSubjectName)
                        .addGap(69, 69, 69)
                        .addComponent(textFieldMateria))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTeacherDropdown)
                            .addComponent(labelGroup)
                            .addComponent(labelWeekDays)
                            .addComponent(labelGroup1))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonDeleteMateria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonAgregarAsignatura))
                            .addComponent(cbElegirTurno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbElegirDia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbElegirDocente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(headerAddSubject)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(textFieldGrupo, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(25, 25, 25))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerAddSubject)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTeacherDropdown)
                    .addComponent(cbElegirDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSubjectName)
                    .addComponent(textFieldMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGroup)
                    .addComponent(textFieldGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbElegirDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWeekDays))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGroup1)
                    .addComponent(cbElegirTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAgregarAsignatura)
                    .addComponent(buttonDeleteMateria))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 176;
        gridBagConstraints.ipady = 185;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 18, 6, 6);
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        mainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonReturnActionPerformed

    private void textFieldNameTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNameTeacherActionPerformed

    }//GEN-LAST:event_textFieldNameTeacherActionPerformed

    private void buttonAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddTeacherActionPerformed
        String nameDocente = textFieldNameTeacher.getText();
        String ciDocente = textFieldCI.getText();
        control.crearDocente(ciDocente, nameDocente);
        textFieldCI.setText("");
        textFieldNameTeacher.setText("");
        cargarDoceTabla();
        cbElegirDocente.removeAllItems();
        listaDocentes();
        cargarAsigTabla();
    }//GEN-LAST:event_buttonAddTeacherActionPerformed

    //aca recorrer todos los docentes
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        listaDocentes();
    }//GEN-LAST:event_formWindowOpened

    private void textFieldCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCIActionPerformed

    private void buttonAgregarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarAsignaturaActionPerformed
        int index = cbElegirDocente.getSelectedIndex(); // Obtener el índice
        
        if (index == -1 || listaDocentes == null) {
            return;
        }
        Docente docente = listaDocentes.get(index);
        String nameSubject = textFieldMateria.getText();
        String group = textFieldGrupo.getText();
        String days = (String) cbElegirDia.getSelectedItem();
        String turno = (String) cbElegirTurno.getSelectedItem();
        
        control.crearAsignatura(docente, nameSubject, group, days, turno);
        textFieldMateria.setText("");
        textFieldGrupo.setText("");
        cargarAsigTabla();
        cargarDoceTabla();
    }//GEN-LAST:event_buttonAgregarAsignaturaActionPerformed

    private void cbElegirTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbElegirTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbElegirTurnoActionPerformed

    private void cbElegirDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbElegirDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbElegirDiaActionPerformed

    private void cbElegirDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbElegirDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbElegirDocenteActionPerformed

    private void buttonDeleteTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteTeacherActionPerformed
        if(doceTabla.getRowCount() > 0){
            if(doceTabla.getSelectedRow() != -1){
                String docenteCi = String.valueOf(doceTabla.getValueAt(doceTabla.getSelectedRow(), 1));
                control.borrarDocente(docenteCi);
                
                mostrarMensaje("Docente se ha eliminado correctamente", "Info", "Docente eliminado");
                cargarDoceTabla();
            }else{
                mostrarMensaje("No se ha seleccionado ningun docente", "Error", "Error al eliminar");
            }
        }else{
            mostrarMensaje("No hay nada para eliminar de la tabla", "Error", "Error al eliminar");
        }
        
    }//GEN-LAST:event_buttonDeleteTeacherActionPerformed

    private void buttonDeleteMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteMateriaActionPerformed
         if(asigTabla.getRowCount() > 0){
            if(asigTabla.getSelectedRow() != -1){
                int asignaturaId = Integer.parseInt(String.valueOf(asigTabla.getValueAt(asigTabla.getSelectedRow(), 0)));
                control.borrarAsignatura(asignaturaId);
                
                mostrarMensaje("La asignatura se ha eliminado correctamente", "Info", "Asignatura eliminado");
                cargarAsigTabla();
            }else{
                mostrarMensaje("No se ha seleccionado ninguna asignatura", "Error", "Error al eliminar");
            }
        }else{
            mostrarMensaje("No hay nada para eliminar de la tabla", "Error", "Error al eliminar");
        }
         
         
    }//GEN-LAST:event_buttonDeleteMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable asigTabla;
    private javax.swing.JButton buttonAddTeacher;
    private javax.swing.JButton buttonAgregarAsignatura;
    private javax.swing.JButton buttonDeleteMateria;
    private javax.swing.JButton buttonDeleteTeacher;
    private javax.swing.JButton buttonReturn;
    private javax.swing.JComboBox<String> cbElegirDia;
    private javax.swing.JComboBox<String> cbElegirDocente;
    private javax.swing.JComboBox<String> cbElegirTurno;
    private javax.swing.JTable doceTabla;
    private javax.swing.JLabel headerAddSubject;
    private javax.swing.JLabel headerAddTeacher;
    private javax.swing.JLabel headerTeacherRegistry;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCI;
    private javax.swing.JLabel labelGroup;
    private javax.swing.JLabel labelGroup1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelSubjectName;
    private javax.swing.JLabel labelTeacherDropdown;
    private javax.swing.JLabel labelWeekDays;
    private javax.swing.JTextField textFieldCI;
    private javax.swing.JTextField textFieldGrupo;
    private javax.swing.JTextField textFieldMateria;
    private javax.swing.JTextField textFieldNameTeacher;
    // End of variables declaration//GEN-END:variables

private void cargarDoceTabla() {
    DefaultTableModel tablaModeldoce = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
            return false;
        }
    };
    
    String titulos[] = {"Nombre", "CI", "Asignatura"};
    tablaModeldoce.setColumnIdentifiers(titulos);
    
    List<Docente> listaDocente = control.traerDocentes();
    
    if(listaDocente != null && !listaDocente.isEmpty()){
        for(Docente d: listaDocente){
            
            if(d.getAsignaturas() != null && !d.getAsignaturas().isEmpty()){
                // Una fila por cada asignatura
                for(Asignatura a : d.getAsignaturas()){
                    Object[] object = {d.getNombreDocente(), d.getCI(), a.getNombreAsignatura()};
                    tablaModeldoce.addRow(object);
                }
            } else {
                // Si no tiene asignaturas, mostrar una sola fila
                Object[] object = {d.getNombreDocente(), d.getCI(), "Sin asignaturas"};
                tablaModeldoce.addRow(object);
            }
        }
    }
    doceTabla.setModel(tablaModeldoce);
}

    private void cargarAsigTabla() {
        DefaultTableModel tablaModelAsig = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        String titulos[] = {"Id", "Asignatura", "Docente", "Grupo", "Día de la semana", "Turno"};
        tablaModelAsig.setColumnIdentifiers(titulos);
        
        List<Asignatura> listaAsignatura = control.traerAsignaturas();
        
        if(listaAsignatura != null && !listaAsignatura.isEmpty()){
            for(Asignatura a: listaAsignatura){            
                Object[] object = {
                    a.getId(),
                    a.getNombreAsignatura(), 
                    a.getDocente().getNombreDocente(), 
                    a.getGrupo(), 
                    a.getDia(), 
                    a.getTurno()
                };
                tablaModelAsig.addRow(object);
            }         
        }      
        asigTabla.setModel(tablaModelAsig);
    }

    public void listaDocentes(){
        cargarDoceTabla();
        cargarAsigTabla();
        listaDocentes = control.traerDocentes();
        if(listaDocentes != null){
            for(Docente d : listaDocentes)
                cbElegirDocente.addItem(d.getCI()); //acá me da el error
            
        } 
        for (Turno t : Turno.values())
            cbElegirTurno.addItem(t.toString());
        
        for (DayOfWeek d : DayOfWeek.values())
            cbElegirDia.addItem(d.toString());
        }
    
    public void mostrarMensaje(String mensaje, String tipo, String titulo){
                JOptionPane optionPane = new JOptionPane(mensaje);
                if(tipo.equals("Info")){
                        optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
                }
                else if(tipo.equals("Error")){
                    optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
                }
                JDialog dialog = optionPane.createDialog(titulo);
                dialog.setAlwaysOnTop(true);
                dialog.setVisible(true);
    }
    
}
